import p1 from './Pics/Product1/p1.webp';
import p2 from './Pics/Product1/p2.webp';
import p3 from './Pics/Product1/p3.webp';
import p4 from './Pics/Product1/p4.webp';
export const CatagoryData=[
    {
        Catagory_name:'Mobiles and Tablets',
        Catagor_Products:[
                            {
                                id:1,
                                product_preview_tile:p1,
                                name:'The Pen',
                                manufacturer:'ABC',
                                previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],   
                                description_short:'',
                                description_long:'',
                                feature:'',
                                price:'',
                                discount:'',
                                availability:'none',
                                    },
                                    {
                                        id:1,
                                        product_preview_tile:p1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    }
                                ]
            
    },
    {
        Catagory_name:'Fashion',
        Catagor_Products:[
                                    {
                                        id:1,
                                        product_preview_tile:p1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    },
                                    {
                                        id:1,
                                        product_preview_tile:p1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    }
                                ]
            
    },
    {
        Catagory_name:'Consumer Electronics',
        Catagor_Products:[
                                    {
                                        id:1,
                                        product_preview_tile:p1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    },
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    }
                                ]
            
    },
    {
        Catagory_name:'Footwear',
        Catagor_Products:[
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    },
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    }
                                ]
            
    },
    {
        Catagory_name:'Home Furnishings',
        Catagor_Products:[
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    },
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    }
                                ]
            
    },
    {
        Catagory_name:'Books',
        Catagor_Products:[
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    },
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    }
                                ]
            
    },
    {
        Catagory_name:'Groceries',
        Catagor_Products:[
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    },
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    }
                                ]
            
    },
    {
        Catagory_name:'Stationary and Craft',
        Catagor_Products:[
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    },
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    }
                                ]
            
    },
    {
        Catagory_name:'Baby Products',
        Catagor_Products:[
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    },
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    }
                                ]
            
    },
    {
        Catagory_name:'Hardwares and essentials',
        Catagor_Products:[
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    },
                                    {
                                        id:1,
                                        name:'The Pen',
                                        manufacturer:'ABC',
                                        previews:[
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p2
                                            },
                                            {
                                                image:p3
                                            },
                                            {
                                                image:p1
                                            },
                                            {
                                                image:p4
                                            }
                                        ],
                                        description_short:'',
                                        description_long:'',
                                        feature:'',
                                        price:'',
                                        discount:'',
                                        availability:'none',
                                        
                                    }
                                ]
            
    }

]