export const ContentBarData=[
    {
        title:'Offers',
        url:'#',
        route:'catagory-product'
    },
    {
        title:'Electronics',
        url:'#',
        route:'catagory-product'
    },
    {
        title:'Fashion',
        url:'#',
        route:'catagory-product'
    },
    {
        title:'Groceries',
        url:'#',
        route:'catagory-product'
    },
    {
        title:'Footware',
        url:'#',
        route:'catagory-product'
    },
    {
        title:'more',
        url:'#',
        route:'catagory-product'
    }
    ];